# Generated by Django 2.2.28 on 2022-08-16 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_tttest'),
    ]

    operations = [
        migrations.AddField(
            model_name='tttest',
            name='tttt',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
